compilateur : main.o analyseur_lexical.o
	gcc -o compilateur main.o analyseur_lexical.o

main.o : 
	gcc -o main.o -c main.c

analyseur_lexical.o : 
	gcc -o analyseur_lexical.o -c analyseur_lexical.c


clean : 
	rm -f *.exe *.o



